#!/bin/bash

if [ $# -ne 1 ]; then
	echo "usage: solve <problem #>"
	exit 1
fi

run_hs() {
	ghc $1 >/dev/null 2>&1 && ./$2
}

run_erl() {
	erlc $1 && erl -noshell -s $2 main -s init stop
}

number=$1
filename=`ls euler$number.{hs,erl} 2> /dev/null | head -n 1`

if [ ! -z $filename ] && [ -f $filename ]; then
	ext="${filename##*.}"
	name="${filename%.*}"
	run_$ext $filename $name
else
	echo "Problem $nbr isn't solved yet"
	exit 1
fi
