#!/bin/bash

if [ $# -ne 1 ]; then
	echo "usage: solve <problem #>"
	exit 1
fi

run_hs() {
    if [ `which ghc` ]; then
        out=`ghc $1`
        res=$?
	    if [ "$res" -eq "0" ]; then
            ./$2
        else
            echo $out
            exit $res
        fi
    else
        echo "Haskell is NOT installed"
        echo
        echo "sudo apt-get install ghc"
        echo "sudo apt-get install cabal-install"
        echo "cabal update"
        echo "cabal install primes"
        exit 1
    fi
}

run_erl() {
    if [ `which erlc` ]; then
	    erlc lists2.erl
	    erlc math2.erl
	    erlc numbers.erl
	    erlc primes.erl
	    erlc $1 && erl -noshell -s $2 main -s init stop
    else
        echo "Erlang is NOT installed"
        exit 1
    fi
}

run_sml() {
    if [ `which sml` ]; then
        sml $1 | grep -v '\['
    else
        echo "SML/NJ is NOT installed"
        echo
        echo "sudo apt-get install smlnj libsmlnj-smlnj"
        exit 1
    fi
}

number=$1
filename=`ls euler$number.{hs,erl,sml} 2> /dev/null | head -n 1`

if [ ! -z $filename ] && [ -f $filename ]; then
	ext="${filename##*.}"
	name="${filename%.*}"
	run_$ext $filename $name
else
	echo "Problem $number isn't solved yet"
	exit 1
fi
